# Numpy

In [1]:
# !pip install numpy

In [2]:
import numpy as np
import time

In [ ]:
a = list(range(100000000))
b = list(range(100000000))

start_t = time.time()
c = [x+y for x,y in zip(a,b)]
end_t = time.time()
time_taken_p = end_t-start_t
print(f"Time taken : {time_taken_p}")

Time taken : 170.3202612400055


In [4]:
a = list(range(100000000))
b = list(range(100000000))
a = np.array(a)
b = np.array(b)

start_t = time.time()
c = a + b
end_t = time.time()
time_taken_n = end_t-start_t
print(f"Time taken : {time_taken_n}")

Time taken : 42.16113352775574


In [5]:
time_taken_p/time_taken_n

4.039745779792172

# 1. np.array()

In [6]:
array_n1 = np.array([1,2,3])

In [7]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int32'>


In [8]:
array_n2 = np.array([1,2,3], dtype=np.int8)
print(type(array_n2))
print(type(array_n2[0]))

<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [9]:
array_n2 = np.array([1,2,"3"], dtype=np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [10]:
array_n2 = np.array([1,2,"3"], dtype=np.float16)
print(array_n2)
print(type(array_n2))
print(type(array_n2[2]))

[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>


# 2. np.arange(start, stop, step)

In [11]:
print(np.arange(5))

print(np.arange(1, 10, 2))

np_arange = np.arange(1, 10, 2)
print(type(np_arange))

[0 1 2 3 4]
[1 3 5 7 9]
<class 'numpy.ndarray'>


# np.linspace(start, stop, num=x)

In [14]:
np_linspace = np.linspace(1,100,4)
print(np_linspace)
print(type(np_linspace))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [13]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# np.zeros(shape)

In [15]:
npz_1 = np.zeros(5)

In [18]:
npz_1.ndim

1

In [19]:
npz_2 = np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
npz_2.ndim

2

In [21]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [22]:
npz_3.ndim

3