# np.zeros()

In [4]:
### np.zeros()
import numpy as np

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.zeros((5,5)).shape

(5, 5)

In [8]:
np.zeros((5,5)).ndim

2

# np.ones()

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# np.full()

In [11]:
# list of size 10, all filled with value 5

In [12]:
np.full((5,5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
np.full((5,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [14]:
np.full(10, 5)
# np.full(shape, fill_value)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# np.eye(n)

In [15]:
np.eye(6, 6, 4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# np.empty(shape)

In [36]:
a = np.full((5,5), 0)

In [37]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [43]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.empty((5,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [35]:
np.empty((5,5), dtype=int)

array([[1138201016,        503,         64,          0,          0],
       [         0,          0,          0,          0,    6357060],
       [ 909260642,  959590502,  962999864, 1717710898, 1714763107],
       [1684420405,  859190626, 1664509026,  959985712,  926049072],
       [ 925906021,  862019938, 1697659234,  959537975, 1630811952]])

In [45]:
import time

perf_counter() is used to get high-resolution time counter.

In [48]:
start_e = time.perf_counter()
np.empty((5, 5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

0.0001721000298857689


In [49]:
start_we = time.perf_counter()
np.ones((5, 5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)

0.00016369996592402458


# np.random.rand(shape)

In [71]:
np.random.rand(5,5)

array([[0.83404213, 0.56871845, 0.55893645, 0.811445  , 0.58786436],
       [0.64588133, 0.68151855, 0.70573133, 0.61199401, 0.19146453],
       [0.15546924, 0.13729596, 0.51849381, 0.72077404, 0.85782623],
       [0.99825123, 0.60140555, 0.69545577, 0.64190428, 0.38903615],
       [0.07924651, 0.11408663, 0.89236139, 0.56949207, 0.88397826]])

In [72]:
a = np.random.rand(10)*10

In [73]:
a = a.tolist()

In [74]:
a

[5.95242576729201,
 4.091162569065033,
 1.662355619928686,
 8.306760411444227,
 4.559095416849227,
 4.800881028275285,
 4.028562622028118,
 6.85117937598335,
 0.6076390205129722,
 1.8093770534929254]

In [75]:
a = [int(i) for i in a]

In [76]:
a

[5, 4, 1, 8, 4, 4, 4, 6, 0, 1]

In [77]:
a

[5, 4, 1, 8, 4, 4, 4, 6, 0, 1]

In [78]:
np.random.randint(1, 11, 10)

array([ 6, 10, 10,  5,  5, 10,  3,  4,  2,  9])

# Questions
- A 1D array of numbers from 0 to 9
- A 3x3 matrix of all 5s
- A 4x4 identity matrix
- 10 evenly spaced numbers between 1 and 100
- A 2x2 array with random values between 0 and 1

# Answers


A 1D array of numbers from 0 to 9
```bash
arr1 = np.arange(10)
print(arr1)
```

A 3x3 matrix of all 5s
```bash
arr2 = np.full((3, 3), 5)
print(arr2)
```

A 4x4 identity matrix
```bash
arr3 = np.eye(4)
print(arr3)
```

10 evenly spaced numbers between 1 and 100
```bash
arr4 = np.linspace(1, 100, 10)
print(arr4)
```

A 2x2 array with random values between 0 and 1
```bash
arr5 = np.random.rand(2, 2)
print(arr5)
```

In [58]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [59]:
arr2 = np.full((3, 3), 5)
print(arr2)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [60]:
arr3 = np.eye(4)
print(arr3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
arr4 = np.linspace(1, 100, 10)
print(arr4)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [62]:
arr5 = np.random.rand(2, 2)
print(arr5)

[[0.40611115 0.95628016]
 [0.61967439 0.04794354]]


# numpy attributes

In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [64]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [65]:
arr.shape

(2, 3)

In [66]:
arr.ndim

2

In [67]:
arr.dtype

dtype('int32')

# ndarray.itemsize

In [68]:
arr.itemsize # size in bytes of one element

4

In [69]:
# 1 gb --> 1024 mb
# 1 mb --> 1024 kb
# 1 kb --> 1024 bytes
# 1 byte --> 8 bit

# Java
# - int --> 4 bytes
# - float --> 4 bytes
# - char --> 1 byte

In [79]:
# import sys

# print("Size of int:", sys.getsizeof(int()))  # Integer
# print("Size of float:", sys.getsizeof(float()))  # Floating-point number
# print("Size of str:", sys.getsizeof(str()))  # String
# print("Size of list:", sys.getsizeof(list()))  # List
# print("Size of tuple:", sys.getsizeof(tuple()))  # Tuple
# print("Size of dict:", sys.getsizeof(dict()))  # Dictionary
# print("Size of set:", sys.getsizeof(set()))  # Set


In [80]:
arr.nbytes # total number of bytes consumed by the array

24

In [81]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [82]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [84]:
a = np.array([[1,2,3], [4,5,6]])

In [85]:
print(a.shape)
print(a.T.shape)

(2, 3)
(3, 2)


In [86]:
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [87]:
z = np.full((3,5),3)
print(z)
z = z.T
print(z)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


# indexing and slicing

In [88]:
arr = np.array([10,20,30,40,50,60])

In [89]:
print(arr[0])
print(arr[-1])

10
60


In [90]:
print(arr[1:4])
print(arr[:3])
print(arr[0:3])

[20 30 40]
[10 20 30]
[10 20 30]


In [91]:
print(arr[::2]) # (start with 0 and step size 2)

[10 30 50]


In [94]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [95]:
print(mat[0,1])
print(mat[1])
print(mat[:,2])
print(mat[:,-1])

2
[4 5 6]
[3 6 9]
[3 6 9]


In [96]:
print(mat[0:2,1:])

[[2 3]
 [5 6]]


In [97]:
arr_temp = np.array([1,2,3,4,5,6,7,8,9])

In [98]:
arr_temp[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [99]:
# [[9, 8, 7],
# [6, 5, 4],
# [3, 2, 1]]

print(mat[::-1, ::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [100]:
arr = np.array([5, 10, 15, 20, 25])

In [101]:
arr>10

array([False, False,  True,  True,  True])

In [102]:
print(arr[arr>10]) # boolean indexing

[15 20 25]


In [103]:
index = [0,3,4]
arr[index]

array([ 5, 20, 25])

In [104]:
arr[0] = 50
print(arr)

[50 10 15 20 25]


# indexing with np.where()

In [105]:
arr = np.array([10, 15, 20, 25, 30])

In [106]:
idx = np.where(arr>20)
print(idx)

(array([3, 4], dtype=int64),)


In [107]:
print(arr[idx])

[25 30]


# array reshaping and resizing

In [108]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [109]:
arr.shape

(6,)

In [110]:
reshaped = arr.reshape(2,3)

In [111]:
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [112]:
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])

In [113]:
reshaped = arr.reshape(3,-1)

In [114]:
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [115]:
reshaped.shape

(3, 4)

In [116]:
a = np.array([[1, 2], [3, 4]])

In [117]:
b = a.flatten()

In [118]:
b

array([1, 2, 3, 4])

In [122]:
a = np.array([1, 2, 3, 4])

In [123]:
a.resize((2,3))

In [124]:
print(a)

[[1 2 3]
 [4 0 0]]


In [125]:
a = np.array([1, 2, 3, 4])

In [126]:
a.resize((2,1))

In [127]:
print(a)

[[1]
 [2]]


In [128]:
# reshape will throw error if values are insufficient
# resize will truncate or padd with zeros

12, (4,5)--> 20 --> reshape will throw error
12, (4,5) --> 20 --> resize, it will pad extra element with 0

12-> 8--> 0

In [129]:
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])
print(a.shape)

(2, 3, 1)


In [130]:
a = np.array([[1],[2],[3]])
print(a.shape)

(3, 1)


In [131]:
a = np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)


In [132]:
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a)
print(b.shape)
print(b)

(2, 3, 1)
(2, 3)
[[1 2 3]
 [1 2 3]]


In [133]:
b = np.squeeze(a)
print(b.shape)
print(b)

(2, 3)
[[1 2 3]
 [1 2 3]]


In [137]:
a = np.array([[[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a, axis=0)
print(b.shape)
print(b)

(1, 3, 1)
(3, 1)
[[1]
 [2]
 [3]]


In [135]:
b = np.array([b])
print(b)

[[[1]
  [2]
  [3]]]


In [138]:
a = np.array([
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ])

In [139]:
print(np.sum(a, axis=0)) # rows wise

[3 6 9]


In [140]:
print(np.sum(a, axis=1)) # column wise

[6 6 6]
